version: '3.8'

services:
  watchdog:
    build: .
    volumes:
      - ./test.txt:/app/test.txt:rw # Ensure the file is writable
    environment:
      - FILE_TO_WATCH=/app/test.txt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
